config/routes.rb
Nimrodaffiliates::Application.routes.draw do
  resources :taxons

  get "manager/dashboard"

  get "manager/affiliates"

  get "manager/taxonomy"

  get "manager/content"

  devise_for :users

  get "public/home"

  get "public/about"

  get "public/contact"

   root :to => 'public#home'

end

app/models/taxon.rb
class Taxon < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name,:user_id
  validates :name,:presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  
  before_filter :authenticate_user!
  
  def dashboard
  end

  def affiliates
  end

  def taxonomy
  end

  def content
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
    if !current_user.nil?
      redirect_to manager_dashboard_path + "#dashboard"     
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController
  # GET /taxons
  # GET /taxons.json
  def index
    @taxons = Taxon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taxons }
    end
  end

  # GET /taxons/1
  # GET /taxons/1.json
  def show
    @taxon = Taxon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxon }
    end
  end

  # GET /taxons/new
  # GET /taxons/new.json
  def new
    @taxon = Taxon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxon }
    end
  end

  # GET /taxons/1/edit
  def edit
    @taxon = Taxon.find(params[:id])
  end

  # POST /taxons
  # POST /taxons.json
  def create
    @taxon = Taxon.new(params[:taxon])

    respond_to do |format|
      if @taxon.save
        format.html { redirect_to @taxon, notice: 'Taxon was successfully created.' }
        format.json { render json: @taxon, status: :created, location: @taxon }
      else
        format.html { render action: "new" }
        format.json { render json: @taxon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taxons/1
  # PUT /taxons/1.json
  def update
    @taxon = Taxon.find(params[:id])

    respond_to do |format|
      if @taxon.update_attributes(params[:taxon])
        format.html { redirect_to @taxon, notice: 'Taxon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxons/1
  # DELETE /taxons/1.json
  def destroy
    @taxon = Taxon.find(params[:id])
    @taxon.destroy

    respond_to do |format|
      format.html { redirect_to taxons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/taxons_helper.rb
module TaxonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nimrod Affiliates" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Nimrod Affiliates</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
            	<li><%= link_to "About", public_about_path  %></li>
              <li><%= link_to "Contact", public_contact_path  %></li>
            <%if !user_signed_in? %>              
              <li><%= link_to "Sign up", new_registration_path(:user) %></li>
              <li><%= link_to "Sign in", new_session_path(:user) %><li>
             <% else %>
             <li><%= link_to('Sign Out',destroy_user_session_path,:method=>:delete)%></li>
             <% end %> 
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
      	<%if user_signed_in? %>  
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Tools</li>
              <li><a href="<%=manager_dashboard_path%>#dashboard" class="btn btn-link"><i class="icon-dashboard"></i> Dashboard</a></li>
              <li><a href="<%=manager_dashboard_path%>#signups" class="btn btn-link"><i class="icon-group"></i> Sign Ups &nbsp;</a></li>
              <li><a href="<%=manager_dashboard_path%>#revenues" class="btn btn-link"><i class="icon-money"></i> Revenues </a></li>
              <li><a href="<%=manager_dashboard_path%>#taxons" class="btn btn-link"><i class="icon-tasks"></i> Taxonomy</a></li>
              <li><a href="<%=manager_dashboard_path%>#mediakit" class="btn btn-link"><i class="icon-picture"></i> Media Kit </a></li>
              <li><a href="<%=edit_user_registration_path%>" class="btn btn-link"><i class="icon-user"></i> Account &nbsp;</a></li>
            </ul>
          </div><!--/.well -->
          </div><!--/span-->
        	<div id="stageHall" class="span9">
          	<%= bootstrap_flash %>
          	<%= yield %>
        	</div>
          <% else %>
          <%= bootstrap_flash %>
          	<%= yield %>
          <% end %>
        
      </div><!--/row-->

      <footer>
        <p align="center"><h5 align="center"><span class="label">&copy; Nimrod Affiliates 2013</span></h5></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/manager/affiliates.html.erb
<h1>Manager#affiliates</h1>
<p>Find me in app/views/manager/affiliates.html.erb</p>

app/views/manager/content.html.erb
<h1>Manager#content</h1>
<p>Find me in app/views/manager/content.html.erb</p>

app/views/manager/taxonomy.html.erb
<h1>Manager#taxonomy</h1>
<p>Find me in app/views/manager/taxonomy.html.erb</p>

app/views/taxons/_form.html.erb
<%= simple_form_for(@taxon) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/taxons/edit.html.erb
<h1>Editing taxon</h1>

<%= render 'form' %>

<%= link_to 'Show', @taxon %> |
<%= link_to 'Back', taxons_path %>

app/views/taxons/index.html.erb
<h1>Listing taxons</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taxons.each do |taxon| %>
  <tr>
    <td><%= taxon.user %></td>
    <td><%= taxon.name %></td>
    <td><%= link_to 'Show', taxon %></td>
    <td><%= link_to 'Edit', edit_taxon_path(taxon) %></td>
    <td><%= link_to 'Destroy', taxon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Taxon', new_taxon_path %>

app/views/taxons/new.html.erb
<h1>New taxon</h1>

<%= render 'form' %>

<%= link_to 'Back', taxons_path %>

app/views/taxons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @taxon.user %>
</p>

<p>
  <b>Name:</b>
  <%= @taxon.name %>
</p>


<%= link_to 'Edit', edit_taxon_path(@taxon) %> |
<%= link_to 'Back', taxons_path %>